### PR TITLE
add "edit profile" button to layout

### PR DESCRIPTION
**Pull request by JamesNix**
Added "edit profile" link to layout, displayed only after signed in.

### CODE REVIEW

**Comment by elizamarcum** [comment]
@JamesNix Please update one of the existing integration tests so that it uses that link to navigate to the use show page.

**Comment by JamesNix** [comment]
Updated integration tests to use link navigation.

**Comment by elizamarcum** [comment]
You've mixed in a commit related to the mailer layouts.  Could you put the mailer layouts code on a separate branch?

**Comment by JamesNix** [comment]
I put the mailer commits on a different branch and deleted all (I think) of
the changes associated with them from the master branch. I don’t think I
remember the proper way to remove the previous commits though. Will this
work?

-James

**Pull request merged**
